-- phpMyAdmin SQL Dump
-- version 4.0.4
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 04, 2014 at 04:26 AM
-- Server version: 5.6.12-log
-- PHP Version: 5.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `users`
--

-- --------------------------------------------------------

--
-- Table structure for table `analysis`
--

CREATE TABLE IF NOT EXISTS `analysis` (
  `type` varchar(5) NOT NULL,
  `id` int(2) NOT NULL,
  `result` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `analysis`
--

INSERT INTO `analysis` (`type`, `id`, `result`) VALUES
('E', 1, 'Your score on this trait is extremely high. You like being with people and having a good time. Your attitude can be characterized as spontaneous and communicative. You are generally less fond of being alone. You are enthusiastic and energetic. You need external stimuli and are generally quickly bored. In a sense, you are always looking for social adventure. It is easy for you to talk and you often lead the troops. To others you are energetic and easy to approach. You are probably very popular among your group of friends. People will generally consider you to be happy and optimistic. It may be difficult for you to take a step back. People who are more introverted may find it difficult to keep up with you, or they may think that your social life is too busy. You generally get along better with people who are relatively talkative and boisterous.'),
('E', 2, 'Your score on this trait is high. You like to have a good time now and then and feel relatively comfortable with others. Your attitude is sometimes characterized as spontaneous and communicative. You do not always enjoy being alone. You can be very enthusiastic and energetic. You sometimes need external stimuli and may be bored quickly. In a sense, you are looking for social adventure. It is easy for you to talk to people and you sometimes take the lead. You can be open and friendly to others. Others probably consider you to be popular. People will generally consider you to be happy and optimistic. It may sometimes be difficult for you to take a step back. People who are highly introverted may find it difficult to keep up with you, or sometimes think your social life is too busy. In general, you get along better with people who are relatively talkative or even boisterous.'),
('E', 3, 'Your score on this trait is above average. You like to have a good time now and then and feel relatively comfortable with others. Your attitude is sometimes characterized as spontaneous and communicative. You do not always enjoy being alone. You can be very enthusiastic and energetic. You sometimes need external stimuli and may be bored quickly. In a sense, you are looking for social adventure. It is easy for you to talk to people and you sometimes take the lead. You can be open and friendly to others. Others probably consider you to be popular. People will generally consider you to be happy and optimistic. It may sometimes be difficult for you to take a step back. People who are highly introverted may find it difficult to keep up with you, or sometimes think your social life is too busy. In general, you get along better with people who are relatively talkative or even boisterous.'),
('E', 4, 'Your score on this trait is just above average. You are equally fond of having fun with others and being alone. In general, you are energetic but not overenthusiastic. You like your privacy but also do well in groups. At parties or in a group, you do not feel a need for attention. If asked or if there is a reason to do so, you will voice your opinion. You do not feel the need to be busy all the time, but you are also not one to simply relax. You feel comfortable with people who are not afraid to take the initiative when the situation arises. But you can also deal with people who are more introverted or who crave attention. You enjoy contact with others, but this is not essential. You can appear to be both hesitant and spontaneous. In principle, an average score on this scale makes you open to both those who are reserved and extroverts.'),
('E', 5, 'Your score on this trait is average. You are equally fond of having fun with others and being alone. In general, you are energetic but not overenthusiastic. You like your privacy but also do well in groups. At parties or in a group, you do not feel a need for attention. If asked or if there is a reason to do so, you will voice your opinion. You do not feel the need to be busy all the time, but you are also not one to simply relax. You feel comfortable with people who are not afraid to take the initiative when the situation arises. But you can also deal with people who are more introverted or who crave attention. You enjoy contact with others, but this is not essential. You can appear to be both hesitant and spontaneous. In principle, an average score on this scale makes you open to both those who are reserved and extroverts.'),
('E', 6, 'Your score on this trait is just below average. You are equally fond of having fun with others and being alone. In general, you are energetic but not overenthusiastic. You like your privacy but also do well in groups. At parties or in a group, you do not feel a need for attention. If asked or if there is a reason to do so, you will voice your opinion. You do not feel the need to be busy all the time, but you are also not one to simply relax. You feel comfortable with people who are not afraid to take the initiative when the situation arises. But you can also deal with people who are more introverted or who crave attention. You enjoy contact with others, but this is not essential. You can appear to be both hesitant and spontaneous. In principle, an average score on this scale makes you open to both those who are reserved and extroverts.'),
('E', 7, 'Your score on this trait is below average. With others, your attitude is somewhat reserved or formal. Your need for external stimuli varies, and you sometimes like being alone. This does not mean that you are anti-social at all. You simply do not always feel the need to be heard or to voice your opinion unasked. You can appear to be reserved and are sometimes less outspoken with others. You may prefer to take things slowly, and you can enjoy being alone. You can be typified as a person who sometimes tests the waters. Others may consider you to be rigid and closed at times. You prefer to be with people who, like yourself, prefer to stay in the background. It is more difficult for you to identify with people who are extremely spontaneous or overly enthusiastic.'),
('E', 8, 'Your score on this trait is low. With others, your attitude is somewhat reserved or formal. Your need for external stimuli varies, and you sometimes like being alone. This does not mean that you are anti-social at all. You simply do not always feel the need to be heard or to voice your opinion unasked. You can appear to be reserved and are sometimes less outspoken with others. You may prefer to take things slowly, and you can enjoy being alone. You can be typified as a person who sometimes tests the waters. Others may consider you to be rigid and closed at times. You prefer to be with people who, like yourself, prefer to stay in the background. It is more difficult for you to identify with people who are extremely spontaneous or overly enthusiastic.'),
('A', 1, 'Your score on this trait is extremely high. This means that above all, you are a people person. Your attitude can be typified as people-minded. You have a mild attitude and are generally empathetic. When dealing with people, you are often helpful and take the other person''s feelings into account. This is evident in your higher level of attentiveness, for example. You will tend to soften bad news, or simply say nothing. Your assessment of others is generally relatively mild. You are probably known to be nice and sociable. You generally have trouble dealing with people who are harsh or unrelenting. As a result, you may sell yourself short or ignore your own needs. Thus you will normally feel comfortable with people whose approach is to be highly considerate of others. You have more trouble dealing with people who are competitive and harsh.'),
('A', 2, 'Your score on this trait is high. This means that you are a person who can be mild and empathetic. In many situations, you understand the emotional side. Your attitude is often considered people-minded. You can be highly empathetic with others. In dealing with people, you will take their feelings into account and can be very helpful. This is then evident in a greater degree of attentiveness. You will tend to soften bad news or simply not give it. You are generally relatively mild in your assessment of others. You are probably known to be nice and sociable. Sometimes you find it difficult to deal with people who are harsh or unrelenting. As a result, you may sell yourself short or ignore your own needs. Remember that some people can be attentive out of self-interest or for a certain purpose. You normally feel more comfortable with people who take others into account by nature. It is generally more difficult for you to deal with highly competitive individuals.'),
('A', 3, 'Your score on this trait is above average. This means that you are a person who can be mild and empathetic. In many situations, you understand the emotional side. Your attitude is often considered people-minded. You can be highly empathetic with others. In dealing with people, you will take their feelings into account and can be very helpful. This is then evident in a greater degree of attentiveness. You will tend to soften bad news or simply not give it. You are generally relatively mild in your assessment of others. You are probably known to be nice and sociable. Sometimes you find it difficult to deal with people who are harsh or unrelenting. As a result, you may sell yourself short or ignore your own needs. Remember that some people can be attentive out of self-interest or for a certain purpose. You normally feel more comfortable with people who take others into account by nature. It is generally more difficult for you to deal with highly competitive individuals.'),
('A', 4, 'Your score on this trait is just above average. You can be very friendly but also relatively direct. In general, you are interested in people and their motives, but can also be business-like. When you do things, you are guided by rationale on the one hand and the circumstances on the other. This means that you can take the feelings of others into account, but can also be relatively direct and less diplomatic. As a result, people will consider you to be both friendly and direct. In other words: a person who is not afraid to say what needs saying, but who is also able to do so in a friendly manner. You get along well with people who are nice but also capable of standing up for themselves. As long as they are not arrogant or individualistic.'),
('A', 5, 'Your score on this trait is average. You can be very friendly but also relatively direct. In general, you are interested in people and their motives, but can also be business-like. When you do things, you are guided by rationale on the one hand and the circumstances on the other. This means that you can take the feelings of others into account, but can also be relatively direct and less diplomatic. As a result, people will consider you to be both friendly and direct. In other words: a person who is not afraid to say what needs saying, but who is also able to do so in a friendly manner. You get along well with people who are nice but also capable of standing up for themselves. As long as they are not arrogant or individualistic.'),
('A', 6, 'Your score on this trait is just below average. You can be very friendly but also relatively direct. In general, you are interested in people and their motives, but can also be business-like. When you do things, you are guided by rationale on the one hand and the circumstances on the other. This means that you can take the feelings of others into account, but can also be relatively direct and less diplomatic. As a result, people will consider you to be both friendly and direct. In other words: a person who is not afraid to say what needs saying, but who is also able to do so in a friendly manner. You get along well with people who are nice but also capable of standing up for themselves. As long as they are not arrogant or individualistic.'),
('A', 7, 'Your score on this trait is below average. In comparison to others, you can be relatively direct. You approach others sometimes in a business-like and sometimes in a somewhat functional manner. As a result, you may leave the impression of being detached. In comparison with others, you are sometimes strong-willed. This means that you are a person who can be competitive. You are not always the first to quickly or spontaneously help others with their personal problems. You may even appear to be somewhat stubborn and business-like to specific others. In the worst case, this may make you seem less nice. However, people can also respect or appreciate you for your direct and outspoken attitude. In general, you get along well with people who, like yourself, are unafraid to be independent and can be straightforward. It is usually more difficult for you to deal with people who tend to be extremely mild or who try to be indirect.'),
('A', 8, 'Your score on this trait is low. In comparison to others, you can be relatively direct. You approach others sometimes in a business-like and sometimes in a somewhat functional manner. As a result, you may leave the impression of being detached. In comparison with others, you are sometimes strong-willed. This means that you are a person who can be competitive. You are not always the first to quickly or spontaneously help others with their personal problems. You may even appear to be somewhat stubborn and business-like to specific others. In the worst case, this may make you seem less nice. However, people can also respect or appreciate you for your direct and outspoken attitude. In general, you get along well with people who, like yourself, are unafraid to be independent and can be straightforward. It is usually more difficult for you to deal with people who tend to be extremely mild or who try to be indirect.'),
('C', 1, 'Your score on this trait is extremely high. You let your conscience lead you. In general, you are highly purposeful and careful. Other typifications that apply are exact and meticulous. You believe that proper preparations are what get the job done. Thus you are generally well organized and have your affairs in order. Others will sometimes think you are overly prudent. You keep your promises and believe that others should as well. You have a strong desire to successfully complete things. Thus you apply your own standards, which others may consider high. You are relatively careful in taking action and like to plan ahead. As a result, you may appear to be inflexible to certain others. Understand that not everybody has the same desire to get things done correctly and successfully. You, however, like to be around people who are neat. People who are generally methodical and careful. Messiness is usually more troubling to you.'),
('C', 2, 'Your score on this trait is high. You let your conscience lead you whenever possible. You are person who is relatively purposeful and careful. Other characteristics that could apply are exact and orderly. You believe that proper preparations are often what get the job done. Thus you are generally well organized and you usually have your affairs in order. Others who are much messier will think you are prudent. In general, you keep your promises and you also often expect others to keep theirs. You have a relatively strong desire to successfully complete things. Thus you sometimes apply your own standards, which others may consider high. You can be relatively cautious and you tend to plan ahead. As a result, you may sometimes appear to be inflexible. Understand that not everybody has the same desire to get things done correctly and successfully. You like to be around people who are neat. People who are methodical and cautious. You may have trouble dealing with people who are extremely messy.'),
('C', 3, 'Your score on this trait is above average. You let your conscience lead you whenever possible. You are person who is relatively purposeful and careful. Other characteristics that could apply are exact and orderly. You believe that proper preparations are often what get the job done. Thus you are generally well organized and you usually have your affairs in order. Others who are much messier will think you are prudent. In general, you keep your promises and you also often expect others to keep theirs. You have a relatively strong desire to successfully complete things. Thus you sometimes apply your own standards, which others may consider high. You can be relatively cautious and you tend to plan ahead. As a result, you may sometimes appear to be inflexible. Understand that not everybody has the same desire to get things done correctly and successfully. You like to be around people who are neat. People who are methodical and cautious. You may have trouble dealing with people who are extremely messy.'),
('C', 4, 'Your score on this trait is just above average. This indicates that you are a person who has his/her affairs reasonably well organized. You like to take a systematic approach without being too prudent. It is probably relatively easy for you to find a healthy balance between your work and your private life. You are the kind of person who can achieve impressive results with relatively little effort. However, striving for perfection is not in your nature. In other words, you are a person who acts to achieve a certain goal but who is willing to compromise. This makes you both effective and flexible, so that many people consider you to be a pleasant colleague or person. In general, you get along well with people who like order and neatness. As long as they are not too persistent.'),
('C', 5, 'Your score on this trait is average. This indicates that you are a person who has his/her affairs reasonably well organized. You like to take a systematic approach without being too prudent. It is probably relatively easy for you to find a healthy balance between your work and your private life. You are the kind of person who can achieve impressive results with relatively little effort. However, striving for perfection is not in your nature. In other words, you are a person who acts to achieve a certain goal but who is willing to compromise. This makes you both effective and flexible, so that many people consider you to be a pleasant colleague or person. In general, you get along well with people who like order and neatness. As long as they are not too persistent.'),
('C', 6, 'Your score on this trait is just below average. This indicates that you are a person who has his/her affairs reasonably well organized. You like to take a systematic approach without being too prudent. It is probably relatively easy for you to find a healthy balance between your work and your private life. You are the kind of person who can achieve impressive results with relatively little effort. However, striving for perfection is not in your nature. In other words, you are a person who acts to achieve a certain goal but who is willing to compromise. This makes you both effective and flexible, so that many people consider you to be a pleasant colleague or person. In general, you get along well with people who like order and neatness. As long as they are not too persistent.'),
('C', 7, 'Your score on this trait is below average. You are capable of taking whatever life brings. Sometimes you seem to be careless. You can be relaxed and spontaneous. However, you are sometimes less organized than others as a result. You may tend to avoid obligations. Your actions are sometimes more intuitive: based on feelings rather than on what has been agreed or is considered appropriate. As a result, sometimes you may appear to be somewhat disorganized and therefore easily distracted. Thus sometimes you need to be careful of forgetting things or losing understanding of the big picture. Specific others will sometimes even consider you to be lazy or uncaring. However, this also means that you can be flexible. In general, you prefer to be with people who take life as it comes. You generally have more difficulty dealing with people who are very cautious, exact or somewhat prudent. You do not always feel at ease in a more structured, extremely orderly environment.'),
('C', 8, 'Your score on this trait is low. You are a person who is usually less organized than others. You may prefer to avoid too many obligations. You take life as it comes and may appear to be careless. Your actions are more intuitive: based on feelings rather than on what has been agreed or is considered appropriate. As a result, you can be somewhat disorganized and therefore easily distracted. Thus you need to be careful of forgetting things or losing understanding of the big picture. Specific others will probably consider you to be lazy or uncaring. However, this also makes you highly flexible. As such, you prefer to be with people who take life as it comes. It is more difficult for you to deal with people who are extremely cautious, exact or basically fussy. You do not feel at ease in a highly structured and orderly environment, and should therefore avoid such situations.'),
('N', 1, 'Your score on this trait is extremely high. This means that in comparison with others, you are generally very calm. When others are stressed, you keep your cool. You are not easily insulted or annoyed. Usually you do not care much about what others think of you. Thus you are relatively untroubled by shame or anger. As a result, you appear to be controlled and satisfied. You are also not easily discouraged. You might appear as indifferent to some people: a person who can remain unmoved and cold-blooded under stress. This can work to your disadvantage, however, when people around you are either enthusiastic or distressed. In such situations, your calm may be interpreted as insensitivity or a lack of enthusiasm. You will get along well with more stable personality types: people known to be cool-headed. Nervous, whiny types who are easily frightened are not normally your type.'),
('N', 2, 'Your score on this trait is high. This means that in comparison with others, you are generally reasonably calm. When others are stressed, you tend to keep your cool. You are not very easily annoyed or insulted. You are less sensitive to what others think of you. Thus you are relatively untroubled by shame or anger. You are also not easily discouraged. As a result, you may appear to be somewhat controlled and satisfied. You are sometimes known as indifferent to some people: a person who can be unmoved and cold-blooded. This can work to your disadvantage, however, when many people around you are enthusiastic or distressed. In such situations, your calm may be interpreted as insensitivity or a lack of enthusiasm. You get along well with more stable personality types: people known to be cool-headed. You sometimes find it more difficult to deal with people who are nervous or whiny.'),
('N', 3, 'Your score on this trait is above average. This means that in comparison with others, you are generally reasonably calm. When others are stressed, you tend to keep your cool. You are not very easily annoyed or insulted. You are less sensitive to what others think of you. Thus you are relatively untroubled by shame or anger. You are also not easily discouraged. As a result, you may appear to be somewhat controlled and satisfied. You are sometimes known as indifferent to some people: a person who can be unmoved and cold-blooded. This can work to your disadvantage, however, when many people around you are enthusiastic or distressed. In such situations, your calm may be interpreted as insensitivity or a lack of enthusiasm. You get along well with more stable personality types: people known to be cool-headed. You sometimes find it more difficult to deal with people who are nervous or whiny.'),
('N', 4, 'Your score on this trait is just above average. This means that you are normally relatively calm. Your emotional response primarily depends on the situation. You only feel stressed or out of balance when put under pressure or forced to deal with setbacks. It is not very difficult to get you riled, and in general you may feel bad about losing, but this does not keep you awake at night. It is relatively easy for you to get past feelings, such as shame. You certainly have your doubts and worries, but these do not dominate your thinking. Most of the time you can think rationally and put emotions into their proper perspective.'),
('N', 5, 'Your score on this trait is average. This means that you are normally relatively calm. Your emotional response primarily depends on the situation. You only feel stressed or out of balance when put under pressure or forced to deal with setbacks. It is not very difficult to get you riled, and in general you may feel bad about losing, but this does not keep you awake at night. It is relatively easy for you to get past feelings, such as shame. You certainly have your doubts and worries, but these do not dominate your thinking. Most of the time you can think rationally and put emotions into their proper perspective.'),
('N', 6, 'Your score on this trait is just below average. This means that you are normally relatively calm. Your emotional response primarily depends on the situation. You only feel stressed or out of balance when put under pressure or forced to deal with setbacks. It is not very difficult to get you riled, and in general you may feel bad about losing, but this does not keep you awake at night. It is relatively easy for you to get past feelings, such as shame. You certainly have your doubts and worries, but these do not dominate your thinking. Most of the time you can think rationally and put emotions into their proper perspective.'),
('N', 7, 'Your score on this trait is below average. You responses are usually relatively alert and involved. However, you may sometimes get overwhelmed by negative feelings, such as fear, shame or anger. It is relatively more difficult for you to get past such feelings. Sometimes your thinking is too negative and you probably worry more than actually necessary. As a result, others may sometimes perceive you to be troubled or tense. The advantage of this is that you will not be easily considered to be cold. Sometimes you devote extra effort to doing things right. As a result, you can be appreciated for your enthusiasm and caring. You prefer being with people who, like you, can be sensitive and empathetic. It is relatively more difficult for you to deal with people who show little enthusiasm or sensitivity. For the record, Emotional stability is the specific scale that fluctuates based on your actual state of mind. Depending on your particular mood or meaningful events in your life, the description given here may apply to a greater or lesser extent.'),
('N', 8, 'Your score on this trait is low. You responses are usually relatively alert and involved. However, you may sometimes get overwhelmed by negative feelings, such as fear, shame or anger. It is relatively more difficult for you to get past such feelings. Sometimes your thinking is too negative and you probably worry more than actually necessary. As a result, others may sometimes perceive you to be troubled or tense. The advantage of this is that you will not be easily considered to be cold. Sometimes you devote extra effort to doing things right. As a result, you can be appreciated for your enthusiasm and caring. You prefer being with people who, like you, can be sensitive and empathetic. It is relatively more difficult for you to deal with people who show little enthusiasm or sensitivity. For the record, Emotional stability is the specific scale that fluctuates based on your actual state of mind. Depending on your particular mood or meaningful events in your life, the description given here may apply to a greater or lesser extent.'),
('O', 1, '1Your score on this trait is extremely high. This means that you are probably a highly imaginative individual. You can also be typified as creative and reflective. You have broad interests and are inquisitive. You are open to new experiences, solutions and values. You love to break with routines and fixed patterns. You are curious and take a broad view of things. Exchanging views and acquiring knowledge are important to you. You do not like routines and fixed patterns. In some ways, others may think of you as curious, exciting or learned. It bothers you when others are not willing to discuss things or insist upon maintaining the status quo. You feel more comfortable with people who are independent or original.'),
('O', 2, 'Your score on this trait is high. This means that you probably have a relatively well-developed imagination. Others will sometimes typify you as being creative or reflective. You sometimes show broad interest and curiosity. You are often open to new experiences, solutions or values. Sometimes you tend to break away from routines and fixed patterns. You are often curious and take a relatively broad view. You enjoy exchanging ideas sometimes or acquiring new knowledge. You are not very fond of routines and fixed patterns. In certain ways, others may consider you to be curious, exciting or learned. You can become troubled when people are afraid to discuss things or insist upon maintaining the status quo. You feel more comfortable with people who can be independent or original.'),
('O', 3, 'Your score on this trait is above average. This means that you probably have a relatively well-developed imagination. Others will sometimes typify you as being creative or reflective. You sometimes show broad interest and curiosity. You are often open to new experiences, solutions or values. Sometimes you tend to break away from routines and fixed patterns. You are often curious and take a relatively broad view. You enjoy exchanging ideas sometimes or acquiring new knowledge. You are not very fond of routines and fixed patterns. In certain ways, others may consider you to be curious, exciting or learned. You can become troubled when people are afraid to discuss things or insist upon maintaining the status quo. You feel more comfortable with people who can be independent or original.'),
('O', 4, 'Your score on this trait is just above average. Part of you is practical. Why make things difficult? But every now and then, with due cause, you will break away from routines or fixed patterns and be open to new ideas, or want to discuss things. You do like challenges and enjoy exchanging views at time. However, finding new ideas and experiences does not always have central focus in your life. In general, you focus on the here and now, but are willing to try something new if necessary or intriguing. Thus your approach is pragmatic. Many people appreciate the fact that you are not constantly wondering whether things can be done differently or better. By nature, you get along well with people who are original without simply refusing to maintain the status quo.'),
('O', 5, 'Your score on this trait is average. Part of you is practical. Why make things difficult? But every now and then, with due cause, you will break away from routines or fixed patterns and be open to new ideas, or want to discuss things. You do like challenges and enjoy exchanging views at time. However, finding new ideas and experiences does not always have central focus in your life. In general, you focus on the here and now, but are willing to try something new if necessary or intriguing. Thus your approach is pragmatic. Many people appreciate the fact that you are not constantly wondering whether things can be done differently or better. By nature, you get along well with people who are original without simply refusing to maintain the status quo.'),
('O', 6, 'Your score on this trait is just below average. Part of you is practical. Why make things difficult? But every now and then, with due cause, you will break away from routines or fixed patterns and be open to new ideas, or want to discuss things. You do like challenges and enjoy exchanging views at time. However, finding new ideas and experiences does not always have central focus in your life. In general, you focus on the here and now, but are willing to try something new if necessary or intriguing. Thus your approach is pragmatic. Many people appreciate the fact that you are not constantly wondering whether things can be done differently or better. By nature, you get along well with people who are original without simply refusing to maintain the status quo.'),
('O', 7, 'Your score on this trait is below average. You are more focused than others on the here and now. Instead of thinking things up or considering alternatives, you prefer to get down to work. Why make things difficult? Thus you are also not the type who readily wants things discussed. As a result, you can seem to be polite and correct. In general, you slightly prefer routine and tend to take a practical approach. Specific others may consider you to be conservative or even rigid as a result, but also especially loyal and rule abiding. It is sometimes difficult for you to deal with people who are dreamy, vague or always wondering whether there is a better way to do things. You prefer to accept things as they are. Your preference is for people who can take a level-headed approach.'),
('O', 8, 'Your score on this trait is low. You are more focused than others on the here and now. Instead of thinking things up or considering alternatives, you prefer to get down to work. Why make things difficult? Thus you are also not the type who readily wants things discussed. As a result, you can seem to be polite and correct. In general, you slightly prefer routine and tend to take a practical approach. Specific others may consider you to be conservative or even rigid as a result, but also especially loyal and rule abiding. It is sometimes difficult for you to deal with people who are dreamy, vague or always wondering whether there is a better way to do things. You prefer to accept things as they are. Your preference is for people who can take a level-headed approach.'),
('N_OBS', 1, 'Your Observers feel that you are very calm and relaxed, even in highly stressful situations '),
('N_OBS', 2, 'Your Observer feel that you are generally calm. Emotionally stable.'),
('N_OBS', 3, 'Your Observers feel that you are slightly emotionally stable. Sometimes able to handle nervousness.'),
('N_OBS', 4, 'Your Observers feel that you are even tempered. You may be nervous sometimes when trying new things'),
('N_OBS', 5, 'Your Observers feel that you get worried sometimes about uncertain outcomes.'),
('N_OBS', 6, 'Your Observers feel that you are mostly nervous & uneasy. Sensitive to environmental stress, shy'),
('N_OBS', 7, 'Your Observers feel that you are highly anxious, easily stressed. You feel depressed mostly. You are very self-conscious and shy');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
